Add cos_secret option to runtime metadata configuration
elyra-ai/elyra pull request #1529
Opened 2021-04-07 01:56 UTC by akchinSTC

This change allows users to specify a secret in the kubernetes
cluster as their credentials to access cloud object storage.

Fixes #1479

- [ ] Add backend tests
- [ ] update documentation on k8s secrets and creation for cos

This change will still require users to have a username and password configured in the runtime in order to push local dependencies to object storage. Specifying a cos_secret will prevent credentials from being exposed in the pipeline yaml and DAG as environmental variables provided the user has created a proper k8s `secret` on the cluster to reference.

This change is narrow in its just for the cos issue. Do we want to spend a little more time and make this more flexible e.g. support secrets in general?

2021-04-07 15:36 UTC, ptitzler commented
> This change is narrow in its just for the cos issue. Do we want to spend a little more time and make this more flexible e.g. support secrets in general?

I think it'd be more important to invest the time instead to add support for volume mounts. 

We should probably also do something (for run and export) to "notify" the user that, if configured,  the pipeline requires the secret to be defined in Kubernetes.

2021-04-07 18:17 UTC, ptitzler commented on elyra/metadata/schemas/airflow.json
> +            "category": "Cloud Object Storage"
While it makes sense to associate it with the `Cloud Object Storage` category, there's going to be a need to support Kubernetes settings that are not part of any of the existing category. (Volume mounts come to mind.) Therefore I would suggest to add this property to a new `Kubernetes` category.

2021-04-07 18:18 UTC, ptitzler commented on elyra/metadata/schemas/airflow.json
> +          "title": "Cloud Object Storage Secret",
```suggestion
          "title": "Cloud Object Storage Credentials Secret",
```

2021-04-07 18:23 UTC, ptitzler commented on elyra/metadata/schemas/airflow.json
> +            "category": "Cloud Object Storage"
I also believe that this puts a stake in the ground, which establishes a Kubernetes settings hierarchy:
- Settings that apply to all pipelines/batch executions that use a specific runtime.
- Runtime settings can optionally be overridden by pipeline settings.
- Pipeline settings can optionally be overridden by node settings.

2021-04-07 18:24 UTC, ptitzler commented on elyra/metadata/schemas/kfp.json
> +          "title": "Cloud Object Storage Secret",
```suggestion
          "title": "Cloud Object Storage Credentials Secret",
```

2021-04-07 18:24 UTC, ptitzler commented on elyra/metadata/schemas/kfp.json
> +            "category": "Cloud Object Storage"
See earlier comment about `Kubernetes` category

2021-04-07 18:26 UTC, ptitzler commented on elyra/metadata/schemas/airflow.json
> +          "description": "Name of the secret stored on the kubernetes host containing the Username and Password",
```suggestion
          "description": "Kubernetes secret that's defined in the specified user namespace, containing the Cloud Object Storage username and password.",
```

2021-04-07 18:27 UTC, ptitzler commented on elyra/metadata/schemas/kfp.json
> +          "description": "Name of the secret stored on the kubernetes host containing the Username and Password",
```suggestion
          "description": "Kubernetes secret that's defined in the specified user namespace, containing the Cloud Object Storage username and password.",
```

2021-04-07 18:35 UTC, ptitzler commented on elyra/templates/airflow/airflow_template.jinja2
> +env_var_secret_id = Secret(deploy_type='env',
Should add a comment before this line indicating that this secret must be defined manually in the user namespace where the pipeline is run.

2021-04-07 18:36 UTC, ptitzler commented on elyra/templates/airflow/airflow_template.jinja2
> +env_var_secret_key = Secret(deploy_type='env',
Should add a comment before this line indicating that this secret must be defined manually in the user namespace where the pipeline is run.

2021-04-08 17:58 UTC, ptitzler commented
In docs/source/user_guide/runtime-conf.md:
- section "Creating a runtime configuration" 
   - there's a typo `Kubeflow Pipeli[n]es ` (not introduced by the PR) in step 2
   - we need to update the screen shot in step 2
   - after step 5 we need a new step 6 for the Kubernetes settings; something like
    ```
   1. Enter the optional Kubernetes information. Refer to section [Kubernetes settings](#kubernetes-settings) for details.
   ```
- section "Cloud Object Storage Credentials Secret (cos_secret)"
  - we should indicate that the secret must be created in the appropriate username space

2021-04-08 18:01 UTC, ptitzler commented on docs/source/user_guide/runtime-conf.md
> +encoded in base64. Learn how to create, deploy, or configure [Kubernetes Secrets](https://kubernetes.io/docs/concepts/configuration/secret/)
```suggestion
encoded in base64. Learn how to create, deploy, or configure [Kubernetes Secrets](https://kubernetes.io/docs/concepts/configuration/secret/).
```

2021-04-08 18:12 UTC, ptitzler commented
Test scenarios:
- [ ] Run pipeline in KFP without secret specified in RTC
- [ ] Run pipeline in KFP with secret specified in RTC and secret defined in cluster
- [ ] Run pipeline in KFP with secret specified in RTC and secret not defined in cluster
- [ ] Export pipeline to KFP to YAML with secret in RTC and secret defined in cluster
- [ ] Export pipeline to KFP to DSL with secret in RTC and secret defined in cluster
- [ ] Run pipeline in AA without secret specified in RTC
- [ ] Run pipeline in AA with secret specified in RTC and secret defined in cluster
- [ ] Run pipeline in AA with secret specified in RTC and secret not defined in cluster
- [ ] Export pipeline to AA DSL without secret specified in RTC
- [ ] Export pipeline to AA DSL with secret specified in RTC and secret defined in cluster
- [ ] Export pipeline to AA DSL with secret specified in RTC and secret not defined in cluster

2021-04-08 19:03 UTC, ptitzler commented
We also need to update the kfp Jinja template to _conditionally_ include a comment https://github.com/elyra-ai/elyra/blob/master/elyra/templates/kfp/kfp_template.jinja2#L58 indicating that the pipeline requires secret {{XYZ}} to be defined in user namespace {{UNS}}. (Like it was done for the AA template)

2021-04-08 19:17 UTC, akchinSTC commented
@ptitzler - thx for the review, im working out a bug with the python export, should've mentioned during the morning calls and why it wasnt shown. should have a fix soon

2021-04-08 19:18 UTC, ptitzler commented
I just ran into that bug (I guess) - Export pipeline to KFP DSL with secret in RTC and secret defined in cluster

2021-04-08 19:52 UTC, ptitzler commented
"Run pipeline in AA with secret specified in RTC and secret not defined in cluster"

Observation: Unfortunately AA doesn't seem to log a clear error message (unlike KFP) that it is unable to access the secret and therefore can't run the pod.

<details><summary>Log Output</summary>
<pre>
```
*** Reading local file: /opt/airflow/logs/test_secret5-0408124323/notebook/2021-04-07T00:00:00+00:00/1.log
[2021-04-08 19:44:17,793] {taskinstance.py:670} INFO - Dependencies all met for <TaskInstance: test_secret5-0408124323.notebook 2021-04-07T00:00:00+00:00 [queued]>
[2021-04-08 19:44:17,824] {taskinstance.py:670} INFO - Dependencies all met for <TaskInstance: test_secret5-0408124323.notebook 2021-04-07T00:00:00+00:00 [queued]>
[2021-04-08 19:44:17,824] {taskinstance.py:880} INFO - 
--------------------------------------------------------------------------------
[2021-04-08 19:44:17,824] {taskinstance.py:881} INFO - Starting attempt 1 of 1
[2021-04-08 19:44:17,826] {taskinstance.py:882} INFO - 
--------------------------------------------------------------------------------
[2021-04-08 19:44:17,850] {taskinstance.py:901} INFO - Executing <Task(NotebookOp): notebook> on 2021-04-07T00:00:00+00:00
[2021-04-08 19:44:17,861] {standard_task_runner.py:54} INFO - Started process 16 to run task
[2021-04-08 19:44:17,890] {standard_task_runner.py:77} INFO - Running: ['airflow', 'run', 'test_secret5-0408124323', 'notebook', '2021-04-07T00:00:00+00:00', '--job_id', '16', '--pool', 'default_pool', '--raw', '-sd', 'DAGS_FOLDER/test_secret5-0408124323.py', '--cfg_path', '/tmp/tmp5apurls7']
[2021-04-08 19:44:17,892] {standard_task_runner.py:78} INFO - Job 16: Subtask notebook
[2021-04-08 19:44:17,967] {logging_mixin.py:112} INFO - Running %s on host %s <TaskInstance: test_secret5-0408124323.notebook 2021-04-07T00:00:00+00:00 [running]> testsecret50408124323notebook-719f2e40e3264a048e848a934ce865ac
[2021-04-08 19:44:18,070] {logging_mixin.py:112} WARNING - /home/airflow/.local/lib/python3.6/site-packages/airflow/kubernetes/pod_launcher.py:330: DeprecationWarning: Using `airflow.contrib.kubernetes.pod.Pod` is deprecated. Please use `k8s.V1Pod`.
  security_context=_extract_security_context(pod.spec.security_context)
[2021-04-08 19:44:18,070] {logging_mixin.py:112} WARNING - /home/airflow/.local/lib/python3.6/site-packages/airflow/kubernetes/pod_launcher.py:77: DeprecationWarning: Using `airflow.contrib.kubernetes.pod.Pod` is deprecated. Please use `k8s.V1Pod` instead.
  pod = self._mutate_pod_backcompat(pod)
[2021-04-08 19:44:18,105] {pod_launcher.py:173} INFO - Event: notebook-e2adebf786694e4e9f71b9fe544ff350 had an event of type Pending
[2021-04-08 19:44:18,106] {pod_launcher.py:139} WARNING - Pod not yet started: notebook-e2adebf786694e4e9f71b9fe544ff350
[2021-04-08 19:44:19,119] {pod_launcher.py:173} INFO - Event: notebook-e2adebf786694e4e9f71b9fe544ff350 had an event of type Pending
[2021-04-08 19:44:19,119] {pod_launcher.py:139} WARNING - Pod not yet started: notebook-e2adebf786694e4e9f71b9fe544ff350
[2021-04-08 19:44:20,131] {pod_launcher.py:173} INFO - Event: notebook-e2adebf786694e4e9f71b9fe544ff350 had an event of type Pending
[2021-04-08 19:44:20,131] {pod_launcher.py:139} WARNING - Pod not yet started: notebook-e2adebf786694e4e9f71b9fe544ff350
[2021-04-08 19:44:21,139] {pod_launcher.py:173} INFO - Event: notebook-e2adebf786694e4e9f71b9fe544ff350 had an event of type Pending
[2021-04-08 19:44:21,139] {pod_launcher.py:139} WARNING - Pod not yet started: notebook-e2adebf786694e4e9f71b9fe544ff350
[2021-04-08 19:44:22,148] {pod_launcher.py:173} INFO - Event: notebook-e2adebf786694e4e9f71b9fe544ff350 had an event of type Pending
[2021-04-08 19:44:22,148] {pod_launcher.py:139} WARNING - Pod not yet started: notebook-e2adebf786694e4e9f71b9fe544ff350
[2021-04-08 19:44:23,158] {pod_launcher.py:173} INFO - Event: notebook-e2adebf786694e4e9f71b9fe544ff350 had an event of type Pending
[2021-04-08 19:44:23,159] {pod_launcher.py:139} WARNING - Pod not yet started: notebook-e2adebf786694e4e9f71b9fe544ff350
[2021-04-08 19:44:24,171] {pod_launcher.py:173} INFO - Event: notebook-e2adebf786694e4e9f71b9fe544ff350 had an event of type Pending
[2021-04-08 19:44:24,171] {pod_launcher.py:139} WARNING - Pod not yet started: notebook-e2adebf786694e4e9f71b9fe544ff350
[2021-04-08 19:44:25,186] {pod_launcher.py:173} INFO - Event: notebook-e2adebf786694e4e9f71b9fe544ff350 had an event of type Pending
[2021-04-08 19:44:25,187] {pod_launcher.py:139} WARNING - Pod not yet started: notebook-e2adebf786694e4e9f71b9fe544ff350
[2021-04-08 19:44:26,200] {pod_launcher.py:173} INFO - Event: notebook-e2adebf786694e4e9f71b9fe544ff350 had an event of type Pending
[2021-04-08 19:44:26,201] {pod_launcher.py:139} WARNING - Pod not yet started: notebook-e2adebf786694e4e9f71b9fe544ff350
[2021-04-08 19:44:27,211] {pod_launcher.py:173} INFO - Event: notebook-e2adebf786694e4e9f71b9fe544ff350 had an event of type Pending
[2021-04-08 19:44:27,211] {pod_launcher.py:139} WARNING - Pod not yet started: notebook-e2adebf786694e4e9f71b9fe544ff350
[2021-04-08 19:44:28,230] {pod_launcher.py:173} INFO - Event: notebook-e2adebf786694e4e9f71b9fe544ff350 had an event of type Pending
[2021-04-08 19:44:28,230] {pod_launcher.py:139} WARNING - Pod not yet started: notebook-e2adebf786694e4e9f71b9fe544ff350
[2021-04-08 19:44:29,244] {pod_launcher.py:173} INFO - Event: notebook-e2adebf786694e4e9f71b9fe544ff350 had an event of type Pending
[2021-04-08 19:44:29,244] {pod_launcher.py:139} WARNING - Pod not yet started: notebook-e2adebf786694e4e9f71b9fe544ff350
[2021-04-08 19:44:30,256] {pod_launcher.py:173} INFO - Event: notebook-e2adebf786694e4e9f71b9fe544ff350 had an event of type Pending
[2021-04-08 19:44:30,256] {pod_launcher.py:139} WARNING - Pod not yet started: notebook-e2adebf786694e4e9f71b9fe544ff350
[2021-04-08 19:44:31,266] {pod_launcher.py:173} INFO - Event: notebook-e2adebf786694e4e9f71b9fe544ff350 had an event of type Pending
[2021-04-08 19:44:31,266] {pod_launcher.py:139} WARNING - Pod not yet started: notebook-e2adebf786694e4e9f71b9fe544ff350
[2021-04-08 19:44:32,290] {pod_launcher.py:173} INFO - Event: notebook-e2adebf786694e4e9f71b9fe544ff350 had an event of type Pending
[2021-04-08 19:44:32,291] {pod_launcher.py:139} WARNING - Pod not yet started: notebook-e2adebf786694e4e9f71b9fe544ff350
[2021-04-08 19:44:33,307] {pod_launcher.py:173} INFO - Event: notebook-e2adebf786694e4e9f71b9fe544ff350 had an event of type Pending
[2021-04-08 19:44:33,307] {pod_launcher.py:139} WARNING - Pod not yet started: notebook-e2adebf786694e4e9f71b9fe544ff350
[2021-04-08 19:44:34,327] {pod_launcher.py:173} INFO - Event: notebook-e2adebf786694e4e9f71b9fe544ff350 had an event of type Pending
[2021-04-08 19:44:34,327] {pod_launcher.py:139} WARNING - Pod not yet started: notebook-e2adebf786694e4e9f71b9fe544ff350
[2021-04-08 19:44:35,337] {pod_launcher.py:173} INFO - Event: notebook-e2adebf786694e4e9f71b9fe544ff350 had an event of type Pending
[2021-04-08 19:44:35,337] {pod_launcher.py:139} WARNING - Pod not yet started: notebook-e2adebf786694e4e9f71b9fe544ff350
[2021-04-08 19:44:36,352] {pod_launcher.py:173} INFO - Event: notebook-e2adebf786694e4e9f71b9fe544ff350 had an event of type Pending
[2021-04-08 19:44:36,352] {pod_launcher.py:139} WARNING - Pod not yet started: notebook-e2adebf786694e4e9f71b9fe544ff350
[2021-04-08 19:44:37,363] {pod_launcher.py:173} INFO - Event: notebook-e2adebf786694e4e9f71b9fe544ff350 had an event of type Pending
[2021-04-08 19:44:37,363] {pod_launcher.py:139} WARNING - Pod not yet started: notebook-e2adebf786694e4e9f71b9fe544ff350
[2021-04-08 19:44:38,374] {pod_launcher.py:173} INFO - Event: notebook-e2adebf786694e4e9f71b9fe544ff350 had an event of type Pending
[2021-04-08 19:44:38,374] {pod_launcher.py:139} WARNING - Pod not yet started: notebook-e2adebf786694e4e9f71b9fe544ff350
[2021-04-08 19:44:39,383] {pod_launcher.py:173} INFO - Event: notebook-e2adebf786694e4e9f71b9fe544ff350 had an event of type Pending
[2021-04-0 [...]

2021-04-08 20:38 UTC, akchinSTC commented
> I just ran into that bug (I guess) - Export pipeline to KFP DSL with secret in RTC and secret defined in cluster

> We also need to update the kfp Jinja template to _conditionally_ include a comment https://github.com/elyra-ai/elyra/blob/master/elyra/templates/kfp/kfp_template.jinja2#L58 indicating that the pipeline requires secret {{XYZ}} to be defined in user namespace {{UNS}}. (Like it was done for the AA template)

Will do, the bug is really more of a syntax and formatting bug right now. The secret that gets plugged into the env variables when using `use_aws_secret` is causing the formatting to go a bit haywire.

2021-04-09 20:44 UTC, ptitzler reviewed
Functionality wise this LGTM. Doc updates still needed -> https://github.com/elyra-ai/elyra/pull/1529#issuecomment-816024302

2021-04-10 00:56 UTC, akchinSTC commented
Updated docs, running into an issue with one of the airflow tests, will try and fix over the weekend. If not, @lresende, we can split into a separate issue and merge this as is.

2021-04-12 17:43 UTC, ptitzler requested changes
![image](https://user-images.githubusercontent.com/13068832/114437792-d9a9d200-9b7b-11eb-81a9-399b2cffe672.png)

2021-04-12 21:46 UTC, ptitzler approved these changes
LGTM

2021-04-13 17:34 UTC, merged