Add component catalog guide to VPE
elyra-ai/elyra pull request #2304
Opened 2021-11-15 23:06 UTC by karlaspuldaro

Closes #2281 
Add guidance about how to add to the component palette from an empty pipeline.

### What changes were proposed in this pull request?
- [x] Override empty canvas with custom message guide
- [x] Add link to [example components repo ](https://github.com/elyra-ai/examples#custom-pipeline-component-examples)
- [x] Bring back drag and drop icon and styling used in 2.2.4 release
- [ ] Open component catalog widget from text link
- [ ] Create separate react component

Current new message:
![image](https://user-images.githubusercontent.com/25207344/141865553-a2884098-4779-4be9-854c-bfd99f2ff712.png)

### How was this pull request tested?

Implementation in progress, no tests added.
 
Developer's Certificate of Origin 1.1

       By making a contribution to this project, I certify that:

       (a) The contribution was created in whole or in part by me and I
           have the right to submit it under the Apache License 2.0; or

       (b) The contribution is based upon previous work that, to the best
           of my knowledge, is covered under an appropriate open source
           license and I have the right under that license to submit that
           work with modifications, whether created in whole or in part
           by me, under the same open source license (unless I am
           permitted to submit under a different license), as indicated
           in the file; or

       (c) The contribution was provided directly to me by some other
           person who certified (a), (b) or (c) and I have not modified
           it.

       (d) I understand and agree that this project and the contribution
           are public and that a record of the contribution (including all
           personal information I submit with it, including my sign-off) is
           maintained indefinitely and may be redistributed consistent with
           this project or the open source license(s) involved.

2021-11-17 22:07 UTC, bourdakos1 commented on packages/pipeline-editor/src/EmptyPipelineContent.tsx
> +const COMPONENT_EXAMPLES_URLl =
is `URLl` a typo?

2021-11-17 22:07 UTC, bourdakos1 approved these changes
Code LGTM

2021-11-17 22:22 UTC, karlaspuldaro commented on packages/pipeline-editor/src/EmptyPipelineContent.tsx
> +const COMPONENT_EXAMPLES_URLl =
It is! lol thx

2021-11-17 22:51 UTC, bourdakos1 commented on packages/pipeline-editor/src/PipelineEditorWidget.tsx
> +          />
Nice! I like this better :)

2021-11-17 23:18 UTC, ptitzler commented
Custom components are not applicable to generic pipelines. Is there a way to only show the extended version of the text in the KFP/AA editors?

2021-11-17 23:28 UTC, ptitzler commented on packages/pipeline-editor/src/EmptyPipelineContent.tsx
> +          or by adding a custom component clicking the{' '}
We should use plural for consistency

```suggestion
          or by adding custom components clicking the{' '}
```

2021-11-18 18:35 UTC, karlaspuldaro commented
Thx @ptitzler, I addressed your comments and updated the screenshot in the PR description.

2021-11-18 18:59 UTC, bourdakos1 requested changes

2021-11-18 18:59 UTC, bourdakos1 commented on packages/pipeline-editor/src/PipelineEditorWidget.tsx
> +          />
Can we break this into two separate components?

Something like:
```tsx
const handleOpenCatalog = () => {
  shell.activateById(`elyra-metadata:${COMPONENT_CATALOGS_SCHEMASPACE}`)
}

{type === undefined ? (
  <EmptyGenericPipeline />
) : (
  <EmptyPlatformSpecificPipeline onOpenCatalog={handleOpenCatalog} />
)}
```

> **Note:** I think you need to rebase, the runtime type stuff has all changed. In this code snippet I use `type` which is `undefined` for "Generic"

2021-11-18 21:31 UTC, bourdakos1 approved these changes
lgtm

2021-11-19 16:09 UTC, ptitzler approved these changes
LGTM

2021-11-19 19:14 UTC, merged