Integration tests for script runner
elyra-ai/elyra pull request #2499
Opened 2022-02-23 15:42 UTC by Hema-Mathiyazhagan

Developer's Certificate of Origin 1.1

       By making a contribution to this project, I certify that:

       (a) The contribution was created in whole or in part by me and I
           have the right to submit it under the Apache License 2.0; or

       (b) The contribution is based upon previous work that, to the best
           of my knowledge, is covered under an appropriate open source
           license and I have the right under that license to submit that
           work with modifications, whether created in whole or in part
           by me, under the same open source license (unless I am
           permitted to submit under a different license), as indicated
           in the file; or

       (c) The contribution was provided directly to me by some other
           person who certified (a), (b) or (c) and I have not modified
           it.

       (d) I understand and agree that this project and the contribution
           are public and that a record of the contribution (including all
           personal information I submit with it, including my sign-off) is
           maintained indefinitely and may be redistributed consistent with
           this project or the open source license(s) involved.

2022-02-23 19:49 UTC, karlaspuldaro requested changes
Hi Hema,
Thank you for addressing previous review comments in #2498
I'd like to add a few more points:
1. If you could please add a detailed description to the PR and link it to the issue it addresses  it'd be helpful to reviewers to understand the purpose of your PR.
2. Since you're using the Python editor for testing, please move the new tests up to Python Tests section to follow current file organization.
3. We want to avoid duplicated code, maybe since you need the open file step from `openFileAndCheckContent` function, I suggest it requires a few tweaks like:
- create a function for opening a file
- create function to check file content
- update existing calls to `openFileAndCheckContent`
- call `openFile` from new tests  - ok to group checking for output tab and buttons on the same test to save some time and steps
- check console output tab and buttons directly in the test body

2022-02-23 23:13 UTC, karlaspuldaro commented on tests/integration/scripteditor.ts
> +    cy.closeTab(-1);
Good catch, although I guess this will close the console output tab, maybe you'd need a second call to close the editor tab.

2022-02-23 23:14 UTC, karlaspuldaro commented on tests/integration/scripteditor.ts
> +    cy.get('button[title="Run"]').click({ force: true });
I think you can remove the `{ force: true }` option since there should be only one element found at this point.

2022-02-24 00:36 UTC, Hema-Mathiyazhagan commented
> Hi Hema, Thank you for addressing previous review comments in #2498 I'd like to add a few more points:
> 
> 1. If you could please add a detailed description to the PR and link it to the issue it addresses  it'd be helpful to reviewers to understand the purpose of your PR.
> 2. Since you're using the Python editor for testing, please move the new tests up to Python Tests section to follow current file organization.
> 3. We want to avoid duplicated code, maybe since you need the open file step from `openFileAndCheckContent` function, I suggest it requires a few tweaks like:
> 
> * create a function for opening a file
> * create function to check file content
> * update existing calls to `openFileAndCheckContent`
> * call `openFile` from new tests  - ok to group checking for output tab and buttons on the same test to save some time and steps
> * check console output tab and buttons directly in the test body

Addressed this comments @karlaspuldaro

2022-02-24 18:27 UTC, karlaspuldaro commented
Looking good all green! 💚
Thank you for addressing the comments.
Just checking if there are more tests you're planning to add to this PR, otherwise I can approve it already.

2022-02-24 20:35 UTC, Hema-Mathiyazhagan commented
> Looking good all green! 💚 Thank you for addressing the comments. Just checking if there are more tests you're planning to add to this PR, otherwise I can approve it already.

@karlaspuldaro  The PR is ready for final review Karla.

2022-02-24 20:54 UTC, karlaspuldaro approved these changes
This looks good! Thank you @Hema-Mathiyazhagan for contributing :)

2022-02-24 20:54 UTC, karlaspuldaro commented on tests/integration/scripteditor.ts
> +    cy.get('span[role="presentation"]').type('print("test")\n');
To clarify, this is being added here as suggested by @ajbozarth to overcome a new code completer element that sometimes blocks the toolbar buttons during testing runtime.

2022-02-24 23:37 UTC, merged