Update user guide to enable elyra[all] install on zsh
elyra-ai/elyra pull request #2839
Opened 2022-07-18 23:01 UTC by leucir

### What changes were proposed in this pull request?
Update user guide to enable elyra[all] install on zsh

Fixes #2834 

 
Developer's Certificate of Origin 1.1

       By making a contribution to this project, I certify that:

       (a) The contribution was created in whole or in part by me and I
           have the right to submit it under the Apache License 2.0; or

       (b) The contribution is based upon previous work that, to the best
           of my knowledge, is covered under an appropriate open source
           license and I have the right under that license to submit that
           work with modifications, whether created in whole or in part
           by me, under the same open source license (unless I am
           permitted to submit under a different license), as indicated
           in the file; or

       (c) The contribution was provided directly to me by some other
           person who certified (a), (b) or (c) and I have not modified
           it.

       (d) I understand and agree that this project and the contribution
           are public and that a record of the contribution (including all
           personal information I submit with it, including my sign-off) is
           maintained indefinitely and may be redistributed consistent with
           this project or the open source license(s) involved.

2022-07-18 23:05 UTC, lresende approved these changes

2022-07-18 23:44 UTC, ptitzler requested changes
I did a quick scan and found one more doc reference in https://github.com/leucir/elyra/blob/fix_doc_install/docs/source/user_guide/pipeline-components.md that we need to update

![image](https://user-images.githubusercontent.com/13068832/179635114-d4b4ce92-3cc7-4105-b16b-bd7bdb48cd85.png)

2022-08-01 15:40 UTC, akchinSTC commented
@leucir - if youre busy i can update this for you and merge. thanks

2022-08-02 23:15 UTC, akchinSTC approved these changes

2022-08-02 23:29 UTC, merged