Covert --valid-only to --include-invalid on list subcommand
elyra-ai/elyra pull request #3142
Opened 2023-03-30 22:14 UTC by kevin-bates

This pull request replaces the `elyra-metadata list` command's `--valid-only` option with `--include-invalid` to make the command more intuitive.  With this change, invalid instances are not listed by default.  Instead, only valid instances are listed and the user must include option `--include-invalid` to have invalid instances included in the output.

The tests were updated accordingly.

Resolves: #2562

2023-03-31 19:03 UTC, lresende approved these changes

2023-04-03 17:34 UTC, ptitzler requested changes
Confirmed that the code changes work as expected, but noticed missing documentation updates. The "listing XXX" sections in the CLI user guide include examples that no longer reflect the new default behavior:
 - https://github.com/elyra-ai/elyra/blob/main/docs/source/user_guide/code-snippets.md#listing-code-snippets
 - https://github.com/elyra-ai/elyra/blob/main/docs/source/user_guide/pipeline-components.md#managing-custom-components-using-the-elyra-cli
 - https://github.com/elyra-ai/elyra/blob/main/docs/source/user_guide/runtime-conf.md#listing-runtime-configurations
 - https://github.com/elyra-ai/elyra/blob/main/docs/source/user_guide/runtime-image-conf.md#managing-runtime-image-configurations-using-the-elyra-cli

2023-04-03 17:52 UTC, ptitzler commented
I added an entry to the _breaking changes_ section in the [release notes draft](https://github.com/elyra-ai/elyra/discussions/3138), which documents the changes and required actions.

2023-04-03 18:05 UTC, ptitzler approved these changes
LGTM! Thank you!

2023-05-06 19:56 UTC, merged